import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import Footer from "../components/footer";
import useLogout from "../hooks/useLogout";

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function Home(props) {
  const router = useRouter();
  const logout = useLogout();
  return (
    <div className={styles.container}>
      <Head>
        <title>Music Pyramid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      
      <main className={styles.mainHome}>
      <h1 className={styles.mainTitle}>Welcome to Music Pyramid </h1>
      <h2>Start your Music Journey</h2>
      <button className={styles.searchBtn}
         onClick={() => {
           if (props.isLoggedIn) {
             router.push("/similarBands");
           } else {
             router.push("/login");
           }
         }}
       >
         SEARCH BANDS
       </button>

      </main>
      <Footer className={styles.footer}/>
      
    </div>
  );
}