
import Head from "next/head";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import dbConnect from "../db/connection";
import Band from "../db/models/bands";
import Header from "../components/header";
import styles from "../styles/myBands.module.css";


export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user || null;
    if (!user) {
      return {
        redirect: { destination: "/login", permanent: false },
      };
    }

    await dbConnect();

    const bands = await Band.find({ userId: user.id || user._id }).lean();

    return {
      props: { user, bands: JSON.parse(JSON.stringify(bands)) },
    };
  },
  sessionOptions
);
    // MyBands page - includes delete button
    export default function MyBands({ user, bands }) {
      const handleDelete = async (id) => {
        const confirmed = confirm ("Delete Band?"); 
        if (!confirmed) return;

        const res = await fetch (`/api/deleteBand?id=${id}`, {
          method: "DELETE",
        });
        if (res.ok) {
          //reload the page
          window.location.reload();
        }else {
          alert("Failed to delete the band");
        }
        };

    return (
    <div className={styles.container}>
      <Head>
        <title>My Saved Bands</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={!!user} username={user?.username} />

      <main className={styles.main}>
        <h1>My Saved Bands</h1>
        {bands.length === 0 ? (
          <p>You have no saved bands.</p>
        ) : (
          <ul className={styles.results_list}>
            {bands.map((band) => (
              <li key={band._id} className={styles.result_item}>
                <div className={styles.artist_card}>
                  {band.image && <img src={band.image} alt={band.name} />}
                  <div>
                    <h3>{band.name}</h3>
                    {band.wiki && (
                      <a href={band.wiki} target="_blank" rel="noreferrer">
                        Wikipedia
                      </a>
                    )}
                    {band.youtube && (
                      <a href={band.youtube} target="_blank" rel="noreferrer">
                        YouTube
                      </a>
                    )}
                    {band.teaser && <p>{band.teaser}</p>}
                      <h2 className={styles.tickets}>Search Tickets</h2>
                      {/* Delete Button css located in myBands*/}
                      <button className={styles.deleteBtn}
                        onClick={() => handleDelete(band._id)}
                      >
                        Delete
                      </button>
                      
                  
                  </div>
                </div>
              </li>
            ))}
          </ul>
        )}
      </main>
      
    </div>
  );
  
}


