import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import useLogout from "../hooks/useLogout";
import NavBar from "../components/NavBar";


export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req, query }) {
    const user = req.session.user || null;
    const userquery = query.userquery || null;
    const apiKey = process.env.TASTEDIVE_API_KEY || "";
    let results = [];
    let error = null;

    if (userquery) {
      const apiUrl = `https://tastedive.com/api/similar?q=${encodeURIComponent(
        userquery
      )}&type=music&info=1&limit=10&k=${apiKey}`;

      try {
        const res = await fetch(apiUrl);
        const data = await res.json();
        results = data?.Similar?.Results || [];


export default function similarBands(props) {
  const router = useRouter();
  const logout = useLogout();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />
      <h1>My Application Similar Bands Page</h1>
      <main className={styles.main}>
      

       
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

